name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Show date
        run: |
          echo date

      - name: Current directory is
        run: |
          echo ls - l
